"""Template generators for `aegis init`.

Produces the content for:
  - .aegis.yml   (project-level config, safe to commit)
  - .aegis/policy.yml   (decision policy, safe to commit)
  - .gitignore patch    (idempotent — never duplicates entries)
"""

from __future__ import annotations

import datetime
from pathlib import Path

# Sentinels written to .gitignore so we can detect them on subsequent runs
_GITIGNORE_MARKER_START = "# Aegis local cache"
_GITIGNORE_ENTRIES = """\
# Aegis local cache
.aegis/cache/

# Aegis local secrets (the .aegis.yml itself is OK to commit; only secrets are local)
.aegis/secrets.env
"""

_VALID_SCANNERS = frozenset({"dependencies", "sast", "secrets", "container"})
_VALID_GATES = frozenset({"critical", "high", "medium", "none"})


def generate_project_config(
    *,
    backend_url: str,
    default_org: str,
    scanners: list[str],
    severity_gate: str,
    policy_file: str = ".aegis/policy.yml",
) -> str:
    """Return the text content for `.aegis.yml`.

    The API token is intentionally excluded — it lives in
    ~/.aegis/config.toml or CI secrets, never in the project repo.
    """
    today = datetime.date.today().isoformat()
    scanner_lines = "\n".join(f"  - {s}" for s in scanners)

    return (
        f"# .aegis.yml — Project-level Aegis configuration\n"
        f"# Generated by `aegis init` on {today}.\n"
        f"\n"
        f"backend_url: {backend_url}\n"
        f"default_org: {default_org}\n"
        f"scanners:\n"
        f"{scanner_lines}\n"
        f"severity_gate: {severity_gate}\n"
        f"policy_file: {policy_file}\n"
    )


def generate_policy() -> str:
    """Return the text content for `.aegis/policy.yml`."""
    return """\
# .aegis/policy.yml — Aegis decision policy
# Determines block / warn / allow verdict from findings

block_on:
  - severity: critical
  - epss_above: 0.7

warn_on:
  - severity: high

allow:
  - default: true

exclude_paths:
  - "tests/**"
  - "**/__pycache__/**"

exclude_packages:
  # Add package names to suppress vulns in known-acceptable deps
  # - example-package@1.2.3
"""


def patch_gitignore(gitignore_path: Path) -> bool:
    """Append Aegis entries to `.gitignore`, idempotently.

    Returns True if entries were added, False if already present.
    """
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")
        if _GITIGNORE_MARKER_START in existing:
            # Already patched — nothing to do
            return False
        # Ensure a newline before appending
        separator = "" if existing.endswith("\n") or not existing else "\n"
        gitignore_path.write_text(
            existing + separator + "\n" + _GITIGNORE_ENTRIES,
            encoding="utf-8",
        )
    else:
        gitignore_path.write_text(_GITIGNORE_ENTRIES, encoding="utf-8")
    return True
