"""add argus_connection table

Revision ID: 113539e19e11
Revises: d8e35101c144
Create Date: 2026-06-28 23:13:33.237390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113539e19e11'
down_revision: Union[str, Sequence[str], None] = 'd8e35101c144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('argus_connection',
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('token_enc', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Forward-only; no downgrade.")
