"""webhook processed-delivery dedup

Revision ID: 25f23cdfe06b
Revises: cf8b88a32db4
Create Date: 2026-07-02 11:43:27.213757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f23cdfe06b'
down_revision: Union[str, Sequence[str], None] = 'cf8b88a32db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_processed_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'delivery_id', name='uq_webhook_delivery_provider_id')
    )
    op.create_index('ix_webhook_deliveries_received_at', 'webhook_processed_deliveries', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Forward-only; no downgrade.")
