"""drop finding_events.org

Revision ID: 4ec44cccdb33
Revises: 65515ca9a9b3
Create Date: 2026-06-08 10:33:39.053298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec44cccdb33'
down_revision: Union[str, Sequence[str], None] = '65515ca9a9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_event_tool_org'), table_name='finding_events')
    op.drop_column('finding_events', 'org')
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Forward-only; no downgrade.")
