"""v2_schema_diff

Revision ID: 52e36215dd4a
Revises: 4f891e8375be
Create Date: 2026-07-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52e36215dd4a'
down_revision: Union[str, Sequence[str], None] = '4f891e8375be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_api_keys_prefix', 'api_keys', ['prefix'], unique=False)
    op.create_index('ix_api_keys_revoked_at', 'api_keys', ['revoked_at'], unique=False)
    op.create_table('argus_connection',
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('token_endpoint', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_enc', sa.String(length=2048), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('external_ref', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_set_hash', sa.String(length=128), nullable=True),
    sa.Column('last_scanned_sha', sa.String(length=64), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_registry', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('source_connection','manual_upload','byo_import')", name='ck_assets_source'),
    sa.CheckConstraint("type IN ('repo','image')", name='ck_assets_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref', name='uq_assets_external_ref')
    )
    op.create_index('ix_assets_source_ref', 'assets', ['source_ref'], unique=False)
    op.create_index('ix_assets_type', 'assets', ['type'], unique=False)
    op.create_table('audit_stream_config',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('auth_token_enc', sa.Text(), nullable=True),
    sa.Column('last_event_id', sa.BigInteger(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_audit_stream_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_image_recommendations',
    sa.Column('image_digest', sa.String(length=80), nullable=False),
    sa.Column('current_ref', sa.Text(), nullable=False),
    sa.Column('current_vuln_count', sa.Integer(), nullable=False),
    sa.Column('recommended_tag', sa.Text(), nullable=True),
    sa.Column('recommended_vuln_count', sa.Integer(), nullable=True),
    sa.Column('candidates_scanned', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('image_digest')
    )
    op.create_table('compliance_control_assessments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.String(length=1024), nullable=True),
    sa.Column('owner_user_id', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assessed_by_user_id', sa.String(length=255), nullable=True),
    sa.Column('assessed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework', 'control_id', name='uq_control_assessment')
    )
    op.create_index('ix_control_assessments_fw', 'compliance_control_assessments', ['framework'], unique=False)
    op.create_table('compliance_control_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.BigInteger(), nullable=True),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('manual', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('suppressed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('suppressed_reason', sa.Text(), nullable=True),
    sa.Column('suppressed_by_user_id', sa.String(length=255), nullable=True),
    sa.Column('suppressed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'framework', 'control_id', name='uq_compliance_mapping_finding_control')
    )
    op.create_index('ix_compliance_finding', 'compliance_control_mappings', ['finding_id'], unique=False)
    op.create_index('ix_compliance_framework_control', 'compliance_control_mappings', ['framework', 'control_id'], unique=False)
    op.create_table('epss_scores',
    sa.Column('cve', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=False),
    sa.Column('scored_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cve')
    )
    op.create_index(op.f('ix_epss_scores_scored_date'), 'epss_scores', ['scored_date'], unique=False)
    op.create_table('frameworks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kev_entries',
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('vendor_project', sa.String(length=120), nullable=True),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('vulnerability_name', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('required_action', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('known_ransomware_use', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cwes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_index(op.f('ix_kev_entries_date_added'), 'kev_entries', ['date_added'], unique=False)
    op.create_table('llm_config',
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('api_key_enc', sa.String(length=512), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('scan_token_budget', sa.Integer(), nullable=False),
    sa.Column('daily_token_budget', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('llm_usage_daily',
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tokens_in', sa.BigInteger(), nullable=False),
    sa.Column('tokens_out', sa.BigInteger(), nullable=False),
    sa.Column('scans', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'date')
    )
    op.create_table('notification_destinations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('destination_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('event_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("destination_type IN ('slack', 'webhook', 'email')", name='ck_notification_destinations_destination_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_notif_dest_name')
    )
    op.create_table('org_settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('logo_data_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_org_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('osv_advisories',
    sa.Column('advisory_id', sa.String(length=64), nullable=False),
    sa.Column('ecosystem', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('kind', sa.String(length=20), server_default='vulnerability', nullable=False),
    sa.Column('blob_key', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('advisory_id')
    )
    op.create_index('ix_osv_advisories_ecosystem', 'osv_advisories', ['ecosystem'], unique=False)
    op.create_index('ix_osv_advisories_modified_at', 'osv_advisories', ['modified_at'], unique=False)
    op.create_table('osv_refresh_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advisories_added', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('advisories_changed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('jobs_enqueued', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_release_dates',
    sa.Column('system', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=256), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('system', 'name', 'version')
    )
    op.create_table('rate_limit_buckets',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name='ck_reports_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_created_by_created_at', 'reports', ['created_by', 'created_at'], unique=False)
    op.create_index('ix_reports_expires_at', 'reports', ['expires_at'], unique=False)
    op.create_table('rule_kill_switches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('killed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('killed_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', name='uq_kill_switch_category')
    )
    op.create_table('rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_dry_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_dry_run_match_count', sa.Integer(), nullable=True),
    sa.Column('dry_run_confirmation_token', sa.String(length=64), nullable=True),
    sa.Column('dry_run_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rules_category', 'rules', ['category'], unique=False)
    op.create_index('ix_rules_enabled', 'rules', ['enabled'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('surface', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'surface', 'name', name='uq_saved_views_user_surface_name')
    )
    op.create_index('ix_saved_views_user_surface', 'saved_views', ['user_id', 'surface'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('schedule_type', sa.String(length=16), nullable=False),
    sa.Column('schedule_value', sa.String(length=64), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('destination_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=16), nullable=True),
    sa.Column('last_run_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("format IN ('pdf', 'csv', 'json')", name='ck_scheduled_reports_format'),
    sa.CheckConstraint("last_run_status IS NULL OR last_run_status IN ('success', 'failed')", name='ck_scheduled_reports_last_run_status'),
    sa.CheckConstraint("report_type IN ('findings', 'posture')", name='ck_scheduled_reports_type'),
    sa.CheckConstraint("schedule_type IN ('simple', 'cron')", name='ck_scheduled_reports_schedule_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_reports_enabled', 'scheduled_reports', ['enabled'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('deadline_days', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('severity', name='uq_sla_policy_severity')
    )
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("provider IN ('github','gitlab','bitbucket','azure_devops','jenkins')", name='ck_webhook_endpoints_provider'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', name='uq_webhook_endpoints_org_provider')
    )
    op.create_index('ix_webhook_endpoints_provider', 'webhook_endpoints', ['provider'], unique=False)
    op.create_table('webhook_processed_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'delivery_id', name='uq_webhook_delivery_provider_id')
    )
    op.create_index('ix_webhook_deliveries_received_at', 'webhook_processed_deliveries', ['received_at'], unique=False)
    op.create_table('framework_controls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework', 'control_id', name='uq_framework_control')
    )
    op.create_index('ix_framework_controls_fw', 'framework_controls', ['framework'], unique=False)
    op.create_table('grants',
    sa.Column('subject_type', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("subject_type IN ('user', 'team')", name='ck_grants_subject_type'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_type', 'subject_id', 'asset_id')
    )
    op.create_index('ix_grants_asset_id', 'grants', ['asset_id'], unique=False)
    op.create_index('ix_grants_subject', 'grants', ['subject_type', 'subject_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('destination_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('delivered', 'failed', 'retry')", name='ck_notif_deliveries_status'),
    sa.ForeignKeyConstraint(['destination_id'], ['notification_destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'event_id', name='uq_notif_delivery_dest_event')
    )
    op.create_index('ix_notif_deliveries_retry', 'notification_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_notif_deliveries_status', 'notification_deliveries', ['status', 'attempted_at'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_rules_priority', 'notification_rules', ['priority'], unique=False)
    op.create_table('osv_vulnerable_ranges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('advisory_id', sa.String(length=64), nullable=False),
    sa.Column('package_name', sa.Text(), nullable=False),
    sa.Column('ecosystem', sa.Text(), nullable=False),
    sa.Column('range_introduced', sa.Text(), nullable=True),
    sa.Column('range_fixed', sa.Text(), nullable=True),
    sa.Column('range_last_affected', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['advisory_id'], ['osv_advisories.advisory_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_osv_ranges_pkg_eco', 'osv_vulnerable_ranges', ['ecosystem', 'package_name'], unique=False)
    op.create_table('posture_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('severity_critical', sa.Integer(), nullable=False),
    sa.Column('severity_high', sa.Integer(), nullable=False),
    sa.Column('severity_medium', sa.Integer(), nullable=False),
    sa.Column('severity_low', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_weight', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_findings', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'snapshot_date', name='uq_posture_snapshot_asset_date')
    )
    op.create_index(op.f('ix_posture_snapshots_asset_id'), 'posture_snapshots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_posture_snapshots_snapshot_date'), 'posture_snapshots', ['snapshot_date'], unique=False)
    op.create_table('rule_violations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_violations_asset_id'), 'rule_violations', ['asset_id'], unique=False)
    op.create_index('ix_rule_violations_rule_status', 'rule_violations', ['rule_id', 'status'], unique=False)
    op.create_index('ix_rule_violations_subject', 'rule_violations', ['subject_type', 'subject_id'], unique=False)
    op.create_index('uq_rule_violations_open_per_subject', 'rule_violations', ['rule_id', 'subject_type', 'subject_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('sbom_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'run_id', name='uq_sbom_runs_asset_run')
    )
    op.create_index('idx_sbom_runs_asset_scanned', 'sbom_runs', ['asset_id', 'scanned_at'], unique=False)
    op.create_table('scim_config',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=True),
    sa.Column('default_role_id', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_scim_config_singleton'),
    sa.ForeignKeyConstraint(['default_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sso_config',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('default_role_id', sa.String(length=255), nullable=True),
    sa.Column('saml_metadata_url', sa.Text(), nullable=True),
    sa.Column('saml_metadata_xml', sa.Text(), nullable=True),
    sa.Column('saml_sp_private_key_enc', sa.Text(), nullable=True),
    sa.Column('saml_sp_certificate', sa.Text(), nullable=True),
    sa.Column('saml_validate_metadata_signature', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('oidc_discovery_url', sa.Text(), nullable=True),
    sa.Column('oidc_client_id', sa.String(length=255), nullable=True),
    sa.Column('oidc_client_secret_enc', sa.Text(), nullable=True),
    sa.Column('oidc_scopes', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_sso_config_singleton'),
    sa.ForeignKeyConstraint(['default_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_signing_secrets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'rotating', 'revoked')", name='ck_webhook_signing_secrets_status'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wss_channel_id_status', 'webhook_signing_secrets', ['channel_id', 'status'], unique=False)
    op.create_index('ix_wss_channel_id_version', 'webhook_signing_secrets', ['channel_id', 'version'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('notif_assignments', sa.Boolean(), nullable=False),
    sa.Column('notif_mentions', sa.Boolean(), nullable=False),
    sa.Column('notif_kev', sa.Boolean(), nullable=False),
    sa.Column('notif_weekly_digest', sa.Boolean(), nullable=False),
    sa.Column('notif_marketing', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('sessions_expires_at_idx', 'user_sessions', ['expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('sessions_user_id_idx', 'user_sessions', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('finding_sla_status',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('breach_age_days', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index('ix_finding_sla_status_breached', 'finding_sla_status', ['breached'], unique=False)
    op.drop_table('team_repositories')
    op.drop_table('team_container_images')
    op.drop_index(op.f('ix_direct_grants_user_id'), table_name='direct_grants')
    op.drop_table('direct_grants')
    op.add_column('audit_events', sa.Column('actor_email', sa.String(length=255), nullable=True))
    op.add_column('audit_events', sa.Column('actor_role', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('resource_type', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('resource_id', sa.String(length=255), nullable=True))
    op.add_column('audit_events', sa.Column('request_method', sa.String(length=8), nullable=True))
    op.add_column('audit_events', sa.Column('request_path', sa.String(length=1024), nullable=True))
    op.add_column('audit_events', sa.Column('request_ip', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('user_agent', sa.String(length=512), nullable=True))
    op.add_column('audit_events', sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_events', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('audit_events', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('audit_events', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.create_index('ix_audit_action_occ', 'audit_events', ['action', 'occurred_at'], unique=False)
    op.create_index('ix_audit_actor_id', 'audit_events', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.add_column('decisions', sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_index(op.f('ix_decision_tool_org'), table_name='decisions')
    op.drop_constraint(op.f('uq_decision_tool_org_key'), 'decisions', type_='unique')
    op.create_index('ix_decisions_asset_identity', 'decisions', ['asset_id', 'tool', 'identity_key'], unique=False)
    op.create_unique_constraint('uq_decision_tool_asset_key', 'decisions', ['tool', 'asset_id', 'identity_key'])
    op.create_foreign_key(None, 'decisions', 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('decisions', 'org')
    op.drop_index(op.f('ix_finding_event_tool_org'), table_name='finding_events')
    op.drop_column('finding_events', 'org')
    op.drop_column('finding_events', 'identity_key')
    op.drop_column('finding_events', 'tool')
    op.add_column('findings', sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('findings', sa.Column('malicious', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('findings', sa.Column('engine', sa.String(length=20), nullable=True))
    op.add_column('findings', sa.Column('detail_blob_key', sa.String(length=512), nullable=True))
    op.add_column('findings', sa.Column('cve_id', sa.String(length=64), nullable=True))
    op.add_column('findings', sa.Column('file_path', sa.String(length=1024), nullable=True))
    op.add_column('findings', sa.Column('title', sa.String(length=512), nullable=True))
    op.add_column('findings', sa.Column('rule_name', sa.String(length=255), nullable=True))
    op.add_column('findings', sa.Column('package_name', sa.String(length=512), nullable=True))
    op.add_column('findings', sa.Column('package_version', sa.String(length=256), nullable=True))
    op.add_column('findings', sa.Column('introduced_by_commit_sha', sa.String(length=64), nullable=True))
    op.add_column('findings', sa.Column('introduced_by_author', sa.String(length=255), nullable=True))
    op.add_column('findings', sa.Column('introduced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('findings', sa.Column('introduced_by_pr_url', sa.String(length=512), nullable=True))
    op.add_column('findings', sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('findings', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('findings', sa.Column('archived_by_rule_id', sa.String(length=64), nullable=True))
    op.add_column('findings', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('assignee_user_id', sa.String(length=255), nullable=True))
    op.add_column('findings', sa.Column('verdict', sa.String(length=20), nullable=True))
    op.add_column('findings', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('findings', sa.Column('exploit_chain', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('verification_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('findings', sa.Column('recommended_fix', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_finding_tool_org_repo'), table_name='findings')
    op.drop_index(op.f('ix_finding_tool_org_severity'), table_name='findings')
    op.drop_index(op.f('ix_finding_tool_org_state'), table_name='findings')
    op.drop_index(op.f('ix_findings_org'), table_name='findings')
    op.drop_constraint(op.f('uq_finding_tool_org_key'), 'findings', type_='unique')
    op.create_index('ix_finding_asset_assignee', 'findings', ['asset_id', 'assignee_user_id'], unique=False)
    op.create_index('ix_finding_asset_severity', 'findings', ['asset_id', 'severity'], unique=False)
    op.create_index('ix_finding_asset_state', 'findings', ['asset_id', 'state'], unique=False)
    op.create_index('ix_findings_archived', 'findings', ['archived'], unique=False)
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index('ix_findings_verdict', 'findings', ['verdict'], unique=False)
    op.create_unique_constraint('uq_finding_tool_asset_key', 'findings', ['tool', 'asset_id', 'identity_key'])
    op.create_foreign_key(None, 'findings', 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'findings', 'users', ['assignee_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('findings', 'org')
    op.drop_column('findings', 'repo')
    op.drop_column('runner_jobs', 'docker_image')
    op.drop_column('runners', 'active_containers')
    op.drop_column('runners', 'scanner_images')
    op.add_column('sbom_components', sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('sbom_components', sa.Column('sbom_id', sa.Integer(), nullable=True))
    op.add_column('sbom_components', sa.Column('license_expression', sa.String(length=512), nullable=True))
    op.add_column('sbom_components', sa.Column('license_category', sa.String(length=32), nullable=True))
    op.add_column('sbom_components', sa.Column('declared_range', sa.String(length=256), nullable=True))
    op.add_column('sbom_components', sa.Column('scope', sa.String(length=16), nullable=True))
    op.add_column('sbom_components', sa.Column('manifest_path', sa.String(length=1024), nullable=True))
    op.add_column('sbom_components', sa.Column('manifest_line', sa.Integer(), nullable=True))
    op.add_column('sbom_components', sa.Column('manifest_snippet', sa.Text(), nullable=True))
    op.add_column('sbom_components', sa.Column('manifest_snippet_start', sa.Integer(), nullable=True))
    op.add_column('sbom_components', sa.Column('layer_digest', sa.String(length=80), nullable=True))
    op.add_column('sbom_components', sa.Column('layer_index', sa.Integer(), nullable=True))
    op.alter_column('sbom_components', 'is_direct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('idx_sbom_components_name'), table_name='sbom_components')
    op.drop_index(op.f('idx_sbom_components_purl'), table_name='sbom_components')
    op.drop_constraint(op.f('uq_sbom_components_org_repo_purl'), 'sbom_components', type_='unique')
    op.create_index('idx_sbom_components_asset_license_cat', 'sbom_components', ['asset_id', 'license_category'], unique=False)
    op.create_index('idx_sbom_components_asset_name', 'sbom_components', ['asset_id', 'name', 'ecosystem'], unique=False)
    op.create_index('idx_sbom_components_asset_purl', 'sbom_components', ['asset_id', 'purl'], unique=False)
    op.create_unique_constraint('uq_sbom_components_asset_purl', 'sbom_components', ['asset_id', 'purl'])
    op.create_foreign_key(None, 'sbom_components', 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sbom_components', 'sboms', ['sbom_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sbom_components', 'org')
    op.drop_column('sbom_components', 'repo')
    op.add_column('sboms', sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('sboms', sa.Column('html_url', sa.String(length=1024), nullable=True))
    op.drop_index(op.f('ix_sboms_org'), table_name='sboms')
    op.drop_constraint(op.f('uq_sbom_org_repo'), 'sboms', type_='unique')
    op.create_index(op.f('ix_sboms_asset_id'), 'sboms', ['asset_id'], unique=False)
    op.create_unique_constraint('uq_sbom_asset', 'sboms', ['asset_id'])
    op.create_foreign_key(None, 'sboms', 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('sboms', 'org')
    op.drop_column('sboms', 'repo')
    op.add_column('scan_checkpoints', sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(None, 'scan_checkpoints', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scan_checkpoints', 'org')
    op.drop_column('scan_checkpoints', 'repo')
    op.add_column('scan_runs', sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('scan_runs', sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('scan_runs', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scan_runs', sa.Column('archived_by_rule_id', sa.String(length=64), nullable=True))
    op.add_column('scan_runs', sa.Column('triggered_by', sa.String(length=20), nullable=True))
    op.add_column('scan_runs', sa.Column('commit_sha', sa.String(length=64), nullable=True))
    op.add_column('scan_runs', sa.Column('branch', sa.String(length=255), nullable=True))
    op.add_column('scan_runs', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.add_column('scan_runs', sa.Column('feedback_status', sa.String(length=20), server_default='not_applicable', nullable=False))
    op.add_column('scan_runs', sa.Column('cancelled_reason', sa.String(length=64), nullable=True))
    op.add_column('scan_runs', sa.Column('failed_scanners', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scan_runs', sa.Column('trigger_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_scanrun_tool_org_status'), table_name='scan_runs')
    op.create_index(op.f('ix_scan_runs_asset_id'), 'scan_runs', ['asset_id'], unique=False)
    op.create_index('ix_scan_runs_feedback_status', 'scan_runs', ['feedback_status'], unique=False)
    op.create_index('ix_scan_runs_pr_number', 'scan_runs', ['pr_number'], unique=False)
    op.create_index('ix_scanrun_archived', 'scan_runs', ['archived'], unique=False)
    op.create_foreign_key(None, 'scan_runs', 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('scan_runs', 'org')
    op.add_column('source_connections', sa.Column('scanners', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('source_connections', sa.Column('connection_methods', postgresql.JSONB(astext_type=sa.Text()), server_default='["pat"]', nullable=False))
    op.add_column('source_connections', sa.Column('sync_schedule_mode', sa.String(length=10), server_default='preset', nullable=False))
    op.add_column('source_connections', sa.Column('sync_schedule_cron', sa.String(length=120), nullable=True))
    op.add_column('source_connections', sa.Column('scan_auto_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('source_connections', sa.Column('scan_schedule_mode', sa.String(length=10), server_default='preset', nullable=False))
    op.add_column('source_connections', sa.Column('scan_schedule_preset', sa.String(length=50), server_default='24h', nullable=False))
    op.add_column('source_connections', sa.Column('scan_schedule_cron', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('sso_subject', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('sso_protocol', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('scim_managed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('uq_users_sso_subject', 'users', ['sso_subject'], unique=True, postgresql_where=sa.text('sso_subject IS NOT NULL'))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Forward-only; no downgrade.")
