"""drop audit_events.org_id

Revision ID: 65515ca9a9b3
Revises: 0f7ba9ee0cf4
Create Date: 2026-06-08 10:26:22.315014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65515ca9a9b3'
down_revision: Union[str, Sequence[str], None] = '0f7ba9ee0cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_org_occurred'), table_name='audit_events')
    op.drop_column('audit_events', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Forward-only; no downgrade.")
