"""drop reports.org

Revision ID: 708dfe4ac7fc
Revises: 4ec44cccdb33
Create Date: 2026-06-08 10:39:10.993489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708dfe4ac7fc'
down_revision: Union[str, Sequence[str], None] = '4ec44cccdb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_org_created_at'), table_name='reports')
    op.create_index('ix_reports_created_by_created_at', 'reports', ['created_by', 'created_at'], unique=False)
    op.drop_column('reports', 'org')
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Forward-only; no downgrade.")
