"""initial_schema

Revision ID: 9de8c6a3b86f
Revises: 
Create Date: 2026-05-18 00:28:58.034214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9de8c6a3b86f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_user_id', sa.String(length=255), nullable=True),
    sa.Column('actor_username', sa.String(length=255), nullable=True),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_created', 'audit_events', ['created_at'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool', sa.String(length=30), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('identity_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool', 'org', 'identity_key', name='uq_decision_tool_org_key')
    )
    op.create_index('ix_decision_tool_org', 'decisions', ['tool', 'org'], unique=False)
    op.create_table('direct_grants',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_grants_user_id'), 'direct_grants', ['user_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool', sa.String(length=30), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=True),
    sa.Column('identity_key', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool', 'org', 'identity_key', name='uq_finding_tool_org_key')
    )
    op.create_index('ix_finding_tool_org_repo', 'findings', ['tool', 'org', 'repo'], unique=False)
    op.create_index('ix_finding_tool_org_severity', 'findings', ['tool', 'org', 'severity'], unique=False)
    op.create_index('ix_finding_tool_org_state', 'findings', ['tool', 'org', 'state'], unique=False)
    op.create_index(op.f('ix_findings_org'), 'findings', ['org'], unique=False)
    op.create_index(op.f('ix_findings_tool'), 'findings', ['tool'], unique=False)
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_data', sa.Text(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_user_read_created', 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runner_heartbeats',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('runner_id', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_used_gb', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heartbeat_runner_received', 'runner_heartbeats', ['runner_id', 'received_at'], unique=False)
    op.create_table('runner_jobs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('runner_id', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('docker_image', sa.String(length=512), nullable=False),
    sa.Column('env_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runner_job_runner_created', 'runner_jobs', ['runner_id', 'created_at'], unique=False)
    op.create_index('ix_runner_job_status_created', 'runner_jobs', ['status', 'created_at'], unique=False)
    op.create_table('runner_tokens',
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('runner_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('runners',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('arch', sa.String(length=50), nullable=False),
    sa.Column('auth_token_hash', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_used_gb', sa.Float(), nullable=True),
    sa.Column('memory_total_gb', sa.Float(), nullable=True),
    sa.Column('disk_used_gb', sa.Float(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('active_containers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scanner_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jobs_completed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sbom_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('purl', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=512), nullable=False),
    sa.Column('ecosystem', sa.String(length=100), nullable=False),
    sa.Column('source_tool', sa.String(length=50), nullable=True),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org', 'repo', 'purl', name='uq_sbom_components_org_repo_purl')
    )
    op.create_index('idx_sbom_components_name', 'sbom_components', ['org', 'name', 'ecosystem'], unique=False)
    op.create_index('idx_sbom_components_purl', 'sbom_components', ['org', 'purl'], unique=False)
    op.create_table('sboms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=255), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org', 'repo', name='uq_sbom_org_repo')
    )
    op.create_index(op.f('ix_sboms_org'), 'sboms', ['org'], unique=False)
    op.create_table('scan_checkpoints',
    sa.Column('tool', sa.String(length=30), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('last_commit_sha', sa.String(length=255), nullable=False),
    sa.Column('last_commit_date', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tool', 'org', 'repo')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('tool', sa.String(length=30), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scanrun_started_at', 'scan_runs', ['started_at'], unique=False)
    op.create_index('ix_scanrun_tool_org_status', 'scan_runs', ['tool', 'org', 'status'], unique=False)
    op.create_index('ix_scanrun_tool_status', 'scan_runs', ['tool', 'status'], unique=False)
    op.create_table('source_connections',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('auth', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scan_scope', sa.String(length=50), nullable=False),
    sa.Column('excluded_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_schedule', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('discovered_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovered_item_count', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=30), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('identity_key', sa.String(length=512), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finding_event_finding_id', 'finding_events', ['finding_id'], unique=False)
    op.create_index('ix_finding_event_tool_org', 'finding_events', ['tool', 'org'], unique=False)
    op.create_table('team_container_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=255), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'org', 'image', name='uq_team_image_team_org_image')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member_team_user')
    )
    op.create_table('team_repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=255), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'org', 'repo', name='uq_team_repo_team_org_repo')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('password_reset_required', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('team_repositories')
    op.drop_table('team_members')
    op.drop_table('team_container_images')
    op.drop_index('ix_finding_event_tool_org', table_name='finding_events')
    op.drop_index('ix_finding_event_finding_id', table_name='finding_events')
    op.drop_table('finding_events')
    op.drop_table('teams')
    op.drop_table('source_connections')
    op.drop_index('ix_scanrun_tool_status', table_name='scan_runs')
    op.drop_index('ix_scanrun_tool_org_status', table_name='scan_runs')
    op.drop_index('ix_scanrun_started_at', table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_table('scan_checkpoints')
    op.drop_index(op.f('ix_sboms_org'), table_name='sboms')
    op.drop_table('sboms')
    op.drop_index('idx_sbom_components_purl', table_name='sbom_components')
    op.drop_index('idx_sbom_components_name', table_name='sbom_components')
    op.drop_table('sbom_components')
    op.drop_table('runners')
    op.drop_table('runner_tokens')
    op.drop_index('ix_runner_job_status_created', table_name='runner_jobs')
    op.drop_index('ix_runner_job_runner_created', table_name='runner_jobs')
    op.drop_table('runner_jobs')
    op.drop_index('ix_heartbeat_runner_received', table_name='runner_heartbeats')
    op.drop_table('runner_heartbeats')
    op.drop_table('roles')
    op.drop_index('ix_notification_user_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('license')
    op.drop_index(op.f('ix_findings_tool'), table_name='findings')
    op.drop_index(op.f('ix_findings_org'), table_name='findings')
    op.drop_index('ix_finding_tool_org_state', table_name='findings')
    op.drop_index('ix_finding_tool_org_severity', table_name='findings')
    op.drop_index('ix_finding_tool_org_repo', table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_direct_grants_user_id'), table_name='direct_grants')
    op.drop_table('direct_grants')
    op.drop_index('ix_decision_tool_org', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_audit_event_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('app_config')
    # ### end Alembic commands ###
