"""add llm transport and anthropic base url

Revision ID: fe63fdb98db5
Revises: f3a2c1d4e5b6
Create Date: 2026-07-23 17:32:58.319304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe63fdb98db5'
down_revision: Union[str, Sequence[str], None] = 'f3a2c1d4e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_config', sa.Column('transport', sa.String(length=16), server_default='auto', nullable=False))
    op.add_column('llm_config', sa.Column('anthropic_base_url', sa.String(length=512), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Forward-only; no downgrade.")
